function table = importMonitor(filename, id, dataLines)
%IMPORTFILE Import data from a text file
%  IEEE13NODECKTMON6506321 = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  IEEE13NODECKTMON6506321 = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  IEEE13NodecktMon6506321 = importfile("C:\Users\USER\OneDrive\Escritorio\USAID\OpenDSS\13Bus\IEEE13Nodeckt_Mon_650632_1.csv", [3, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 05-Mar-2023 20:04:32

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 3
    dataLines = [3, Inf];
end
if nargin < 2
    id = 0;
end
%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 14);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
VariableNames = ["Var1", "Var2", "V1", "VAngle1", "V2", "VAngle2", "V3", "VAngle3", "I1", "IAngle1", "I2", "IAngle2", "I3", "IAngle3"];
SelectedVariableNames = ["V1", "VAngle1", "V2", "VAngle2", "V3", "VAngle3", "I1", "IAngle1", "I2", "IAngle2", "I3", "IAngle3"];

opts.VariableTypes = ["string", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
opts.VariableNames = VariableNames;
opts.SelectedVariableNames = SelectedVariableNames;

id_str = sprintf("_%s", id);

for i = 1:length(SelectedVariableNames)
    new_varname = strcat(SelectedVariableNames(i), id_str);
    SelectedVariableNames(i) = new_varname;
end

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2"], "EmptyFieldRule", "auto");

% Import the data
table = readtable(filename, opts);

% Correct Files
nans = nnz(isnan(table2array(table)));
if nans == 4
    table.IAngle2 = table.IAngle1;
    table.I2 = table.I1;
    table.IAngle1 = table.VAngle3;
    table.I1 = table.V3;
    table.VAngle3 = nan;
    table.V3 = nan;
elseif nans == 8
    table.IAngle1 = table.VAngle2;
    table.I1 = table.V2;
    table.VAngle2 = nan;
    table.V2 = nan;
end
table.Properties.VariableNames = SelectedVariableNames;

end