%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\USER\OneDrive\Escritorio\USAID\OpenDSS\13Bus\Exported\test_losses.csv
%
% Auto-generated by MATLAB on 07-Jan-2023 20:23:44

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Element", "TotalW", "Totalvar", "I2RW", "I2Xvar", "NoloadW", "Noloadvar"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
%opts = setvaropts(opts, "Element", "TrimNonNumeric", true);
%opts = setvaropts(opts, "Element", "ThousandsSeparator", ",");

% Import the data
losses = readtable("C:\Users\USER\OneDrive\Escritorio\USAID\OpenDSS\13Bus\Exported\test_losses.csv", opts);
total_loss = sum(losses.TotalW);

%% Clear temporary variables
clear opts