%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\USER\OneDrive\Escritorio\USAID\OpenDSS\13Bus\Exported\test_powers.csv
%
% Auto-generated by MATLAB on 07-Jan-2023 21:17:52

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Element", "Terminal", "PMW", "QMvar", "P_Normal", "Q_Normal", "P_Emergency", "Q_Emergency"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Element", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Element", "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["Terminal", "PMW", "QMvar", "P_Normal", "Q_Normal", "P_Emergency", "Q_Emergency"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["Terminal", "PMW", "QMvar", "P_Normal", "Q_Normal", "P_Emergency", "Q_Emergency"], "ThousandsSeparator", ",");

% Import the data
powers = readtable("C:\Users\USER\OneDrive\Escritorio\USAID\OpenDSS\13Bus\Exported\test_powers.csv", opts);
total_power = sum(powers.PMW);

%% Clear temporary variables
clear opts